### ISSUE TITLE
Repository setup

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/antsibull-docs-parser#1]
Hi @gotmax23, I've created a new repo and copied the code over, but added no project structure yet (which also means that the code is pretty untested as-is ;-) ). I'll probably play around a bit and create a PR to see how it goes.

I plan to make the repo public as soon as a basic structure is there and a 0.0.1 version can be published (to reserve the name).

**Comment by gotmax23** [comment]
We setup the repo in #2 and released 0.0.1!
